server:
  port: 9090
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    jdbc-url: ENC(F569Wb4PMcSPZlENgatqPK4jD1a6m77m3qdL/E3kTnVwZ/ob8vt2fWqe6bg8kiAw5oYcw8wIt6JHorSy8z6Nmg==)
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: ENC(lbev09K62wfWB4gPZuxVBzdgG4WVN5vB8Uru7jhweYq4/qU1L05JHB6mGBnV9B1d7v63Ak9CM5g=)
    username: ENC(LoVBvkHceiW3h0bJfKGZ4g==)
    password: ENC(rpeuCKJN4S5KOCf362ZH5A==)
  devtools:
    livereload:
        enabled: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**
    favicon:
      enabled: false
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 31536000
      chain:
        strategy:
          fixed:
            enabled: true
            version: 20221029-1
          #  web:
          #    resources:s
          #        static-locations: classpath:static/
          #    mybatis:
          #        configuration:
          #            map-underscore-to-camel-case: true
          #mybatis.configuration.return-instance-for-empty-row=false
jasypt:
  encryptor:
#    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

