server:
  port: 9090
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource1:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    jdbc-url: ENC(F569Wb4PMcSPZlENgatqPK4jD1a6m77m3qdL/E3kTnVwZ/ob8vt2fWqe6bg8kiAw5oYcw8wIt6JHorSy8z6Nmg==)
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: ENC(lbev09K62wfWB4gPZuxVBzdgG4WVN5vB8Uru7jhweYq4/qU1L05JHB6mGBnV9B1d7v63Ak9CM5g=)
    username: ENC(LoVBvkHceiW3h0bJfKGZ4g==)
    password: ENC(rpeuCKJN4S5KOCf362ZH5A==)
  datasource2:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    jdbc-url: ENC(F569Wb4PMcSPZlENgatqPK4jD1a6m77m3qdL/E3kTnVwZ/ob8vt2fWqe6bg8kiAw5oYcw8wIt6JHorSy8z6Nmg==)
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: ENC(lbev09K62wfWB4gPZuxVBzdgG4WVN5vB8Uru7jhweYq4/qU1L05JHB6mGBnV9B1d7v63Ak9CM5g=)
    username: ENC(qTbbqN2iMpvPD6PPfQeELA==)
    password: ENC(nDW5tU9l95j7PBy1d+JW/A==)
  devtools:
    livereload:
        enabled: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**
    favicon:
      enabled: false
  web:
    resources:
      #static-locations: classpath:static/
      cache:
        cachecontrol:
          max-age: 31536000
      chain:
        strategy:
          fixed:
            enabled: true
            version: 20221029-1
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: eed7fb5b00b830
    password: df9b38c9fe8200
    properties:
      mail:
        debug: true
        smtp:
          connectiontimeout: 5000
          auth: false
          starttls:
            enable: true
          ssl:
            enable: false
jasypt:
  encryptor:
    #bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

