spring:
    db1:
        datasource:
            driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
            jdbc-url: jdbc:log4jdbc:mariadb://146.56.164.175:3306/testdb?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
            username: admin
            password: sung1q2w3e
            maximum-pool-size: 50
            max-lifetime: 30000
            idle-timeout: 28000
            connection-timeout: 0
            transaction-isolation: TRANSACTION_READ_UNCOMMITTED
    db2:
        datasource:
            driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
            jdbc-url: jdbc:log4jdbc:oracle:thin:@146.56.164.175:1521/xe
            username: SUNG
            password: 1234
    devtools:
        livereload:
            enabled: true
    thymeleaf:
        prefix: classpath:templates/
        suffix: .html
        cache: false
    mvc:
        static-path-pattern: /static/**
    resources:
        static-locations: classpath:/static/
