# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Deliver File
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        source: "build/libs/*.jar"
        target: "source"
        rm: true

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          SOURCE_DIR=source/build/libs
          FILE_NAME=`find $SOURCE_DIR/*.jar -printf "%f\n"`
          PID=`ps -ef | grep $SOURCE_DIR/$FILE_NAME | awk '{print $2}'`

          if [ -z "$PID" ]; then
                  echo "#### THERE IS NO PROCESS ####"
          else
                  echo "#### KILL $PID ####"
                  sudo kill $PID
          fi

          echo "#### RUN $SOURCE_DIR/$FILE_NAME ####"

          sudo nohup java -jar $SOURCE_DIR/$FILE_NAME &
